### ISSUE TITLE
What Object categories are in LaRS panoptic dataset

### ISSUE THREAD

**Issue by matheusns** [lojzezust/mmsegmentation-macvi#1]
The object category IDs list is not documented on the LaRS panoptic dataset. 
 
 This is important information to share with the community as it is relevant to using the dataset properly. 
 
 Thanks in advance.

**Comment by lojzezust** [comment]
Hi. The panoptic object category IDs are documented in the panoptic JSON annotations in the field `categories` and described in more detail in [our paper](https://arxiv.org/abs/2308.09618). Here is a summary:

```
[{'id': 1, 'name': 'Static Obstacle', 'supercategory': 'obstacle'},
 {'id': 3, 'name': 'Water', 'supercategory': 'water'},
 {'id': 5, 'name': 'Sky', 'supercategory': 'sky'},
 {'id': 11, 'name': 'Boat/ship', 'supercategory': 'obstacle'},
 {'id': 12, 'name': 'Row boats', 'supercategory': 'obstacle'},
 {'id': 13, 'name': 'Paddle board', 'supercategory': 'obstacle'},
 {'id': 14, 'name': 'Buoy', 'supercategory': 'obstacle'},
 {'id': 15, 'name': 'Swimmer', 'supercategory': 'obstacle'},
 {'id': 16, 'name': 'Animal', 'supercategory': 'obstacle'},
 {'id': 17, 'name': 'Float', 'supercategory': 'obstacle'},
 {'id': 19, 'name': 'Other', 'supercategory': 'obstacle'}]
```

For the semantic segmentation masks the ids are the following:
```
OBSTACLES: 0 (everything that is under supercategory 'obstacle')
WATER: 1
SKY: 2
IGNORE: 255
```

**Comment by lojzezust** [comment]
For clarity, I've also added this information to the [LaRS homepage](https://lojzezust.github.io/lars-dataset/).

**Comment by matheusns** [comment]
Thanks a lot for clarifying it. It should save more time for people from now on.
